#!/bin/bash

## Run eww daemon if not running already
if [[ ! `pidof eww` ]]; then
    eww daemon
    eww open-many bar
    echo "Bar launched..."
else
    eww close bar system calendar audio_ctl music_win > /dev/null
    killall -q eww
    echo "Bar closed..."
fi
