#!/bin/bash

active_window_title()
{
   hyprctl activewindow -j | jq  -Mc '{class, title, pid}'
}


active_window_title
socat -u UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
    active_window_title
done
