#! /bin/sh

# wallpaper
swww init
swww img --transition-step=30  ~/Pictures/wallpapers/craig-nacroix-dokkaebi.png

# eww status bar
$HOME/.local/bin/eww -c $HOME/.config/eww/bar --restart open bar &

# input method
fcitx5 &

## steam and github proxy
cd /opt/steamcommunity_302/ && ./caddy run \
    --config steamcommunity_302.caddy.json \
    --adapter caddyfile &
