#! /bin/sh

# wallpaper
swww init
swww img --transition-step=30  ~/Pictures/wallpaper/swimming_cat.png

# waybar
#waybar -c $HOME/.config/hypr/waybar/config -s $HOME/.config/hypr/waybar/style.css &

# input method
fcitx5 &
