#! /bin/bash

# use nmcli to connect network
nmcli device wifi list | \
    fzf --header-lines=1 --header="Press CTRL-R to rescan." \
        --prompt="choose a network to connect..." --bind 'ctrl-r:reload(nmcli device wifi list)' \
        --bind 'enter:execute($HOME/.local/scripts/nmcli_passwd {2} {1})'+accept >/dev/null
