#! /bin/sh

# swww set image wallpaper
swww init
swww img ~/Pictures/wallpapers/craig-nacroix-dokkaebi.png

# mpvpaper set video wallpaper
mpvpaper -o "input-ipc-server=/tmp/mpv-socket no-audio --loop-file" eDP-1 ~/Pictures/wallpapers/animate/Karuha-1080p.mp4 &

# screenshots: flameshot
# /usr/local/bin/flameshot &

# eww bar
#eww daemon
eww open bar

# set cursor theme
hyprctl setcurosr XCURSOR_THEME XCURSOR_SIZE

#wl-paste --watch cliphist store
# eww status bar
# eww open-many left_bar

# input method
fcitx5 &

## steam and github proxy
#cd /opt/steamcommunity_302/ && ./caddy run \
#    --config steamcommunity_302.caddy.json \
#    --adapter caddyfile &
